export const REQUEST_PROPERTIES_SUCCESS = 'REQUEST_PROPERTIES_SUCCESS';
export const REQUEST_PROPERTIES_FALIURE = 'REQUEST_PROPERTIES_FALIURE';
export const REQUEST_USER_PROPERTIES_SUCCESS = 'REQUEST_USER_PROPERTIES_SUCCESS';
export const REQUEST_USER_PROPERTIES_FALIURE = 'REQUEST_USER_PROPERTIES_FALIURE';
export const SET_CURRENT_PROPERTY = 'SET_CURRENT_PROPERTY';
export const SET_PROPERTY_FIELD = 'SET_PROPERTY_FIELD';
export const POST_PROPERTIES_SUCCESS = 'POST_PROPERTIES_SUCCESS';
export const POST_PROPERTIES_FALIURE = 'POST_PROPERTIES_FALIURE';