export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAILURE = 'REQUEST_USER_FAILURE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_FIELD = 'SET_USER_FIELD';